name: Build and publish a release
on:
  push:
    tags: ["*"]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Build the package
        run: |
          npm install
          npm run build
      - name: Prepare files for archiving
        env:
          FILES: package.json package-lock.json dist
        run: |
          mkdir luminar
          cp -r $FILES luminar
      - name: Archive the built package
        uses: TheDoctor0/zip-release@0.7.6
        with:
          type: tar
          path: luminar
          filename: release.tar.gz
      - name: Create a release and publish the archive
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: release.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
