name: Build and deploy documentation
on:
  push:
    branches: ["main"]
    tags: ["*"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Build the Storybook documentation
        run: |
          TAG=$(git describe --tags --abbrev=0 2> /dev/null || git rev-parse --abbrev-ref HEAD)
          sed -i "s/\"devel\"/\"$TAG\"/g" .storybook/manager-head.html
          npm install
          npm run build-storybook
      - name: Deploy the built pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
